[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "TimZGUI"
version = "1.1.0"
dependencies = [
    "mysql",
]

[project.scripts]
gui = "interface.gui:run"